description: >
  DistMult - https://www.microsoft.com/en-us/research/publication/embedding-entities-and-relations-for-learning-and-inference-in-knowledge-bases/

parent_config: './conf/jack.yaml'
loader: jack

reader: 'distmult_reader'

train: 'data/WN18/train.jtr'
dev: 'data/WN18/valid.jtr'
test: 'data/WN18/test.jtr'

seed: 1337
epochs: 100
repr_dim: 200

batch_size: 32
optimizer: adagrad
learning_rate: 0.1
learning_rate_decay: 1.0
