description: >
  DistMult - https://www.microsoft.com/en-us/research/publication/embedding-entities-and-relations-for-learning-and-inference-in-knowledge-bases/

parent_config: './conf/jack.yaml'
loader: jack

reader: 'distmult_reader'




seed: 1337
epochs: 100
repr_dim: 20

optimizer: adagrad
learning_rate: 0.1
learning_rate_decay: 1.0
