description: >
  A configuration inheriting from the default jack.yaml

parent_config: './conf/snli.yaml'

# Reader model to use, see jack/readers/implementations.py for options
model: 'dam_snli_reader'

# fixed experiment seed
seed: 1337

repr_dim: 300

epochs: 20

dropout: 0.5

batch_size: 64

lowercase: False

