description: >
  A configuration inheriting from the default jack.yaml

parent_config: './conf/jack.yaml'

# Reader model to use, see jack/readers/implementations.py for options
model: 'dam_reader'

# fixed experiment seed
seed: 1337

# loader to use in experiment
loader: 'snli'

# where to store the reader
model_dir: './dam_reader'

# jack training file
train: 'data/SQuAD/train-v1.1.json'

# jack dev file
dev: 'data/SQuAD/dev-v1.1.json'

# jack test file
test: null

# [word2vec], [glove] or [memory_map_dir] format of embeddings to be loaded
embedding_format: 'memory_map_dir'

# embeddings to be loaded
embedding_file: 'data/GloVe/glove.840B.300d.memory_map_dir'

# Use fixed vocab of pretrained embeddings
vocab_from_embeddings: True

repr_dim: 300

epochs: 400

dropout: 0.5

batch_size: 32
