config_filename: extractive_qa.yaml

description: >
  A configuration inheriting from the default jack.yaml

parent_config: './conf/jack.yaml'

# where to store the reader
model_dir: './fastqa_reader'

# How large the support should be. Can be used for cutting or filtering QA examples
max_support_length: -1

# Use also character based embeddings in readers which support it
with_char_embeddings: False

# jtr training file
train: ['data/SciQ/train.json','data/SQuAD/train.json']

# jtr dev file
dev: ['data/SciQ/dev.json','data/SQuAD/dev.json']

# jtr test file
test: null

# Reading model to use
model: 'fastqa_reader'

# [word2vec] or [glove] format of embeddings to be loaded
embedding_format: 'glove'

# format of embeddings to be loaded
embedding_file: 'data/GloVe/glove.6B.50d.txt'

# Use fixed vocab of pretrained embeddings
vocab_from_embeddings: True

# Use pretrained embeddings, by default the initialisation is random
pretrain: True

# Size of the input representation (embeddings),
# default 128 (embeddings cut off or extended if not,
# matched with pretrained embeddings)
repr_dim_input: 300

# Size of the hidden representations, default 128
repr_dim: 300

# Probability for dropout on output (set to 0.0 for no dropout)
dropout: 0.5

# Learning rate, default 0.001
learning_rate: 0.001

# Batch size for training data, default 128
batch_size: 128