description: >
  Basic multiple choice configuration.

parent_config: './conf/jack.yaml'

# Reader model to use, see jack/readers/implementations.py for options
model: 'dam_snli_reader'

# loader for the dataset, ['jack', 'squad', 'snli'] are supported. For everything else convert to jtr format first.
loader: snli

# SNLI training file
train: 'data/SNLI/snli_1.0/snli_1.0_train.jsonl'

# SNLI dev file
dev: 'data/SNLI/snli_1.0/snli_1.0_dev.jsonl'

# SNLI test file
test: 'data/SNLI/snli_1.0/snli_1.0_test.jsonl'

epochs: 20

repr_dim: 300

embedding_format: 'memory_map_dir'

embedding_file: 'data/GloVe/glove.840B.300d.memory_map_dir'

# Use fixed vocab of pretrained embeddings
vocab_from_embeddings: True

# Use also character based embeddings in readers which support it
with_char_embeddings: False

repr_dim: 300

epochs: 400

dropout: 0.5

batch_size: 32

lowercase: False

